export const actionsEnums = {
  MEMBERS_REQUEST: 'MEMBERS_REQUEST',
  MEMBERS_REQUEST_COMPLETED: 'MEMBERS_REQUEST_COMPLETED',
  UPDATE_ORGANIZATION: '[0] Updates the organization',
  UPDATE_MEMBER: '[0] Updates the member',
  MEMBER_REQUEST: 'MEMBER_REQUEST',
  MEMBER_REQUEST_COMPLETED: 'MEMBER_REQUEST_COMPLETED',
}
